import 'dotenv/config'

/* TOKEN GERADO NA MOVINGPAY EM *OPERACIONAL -> USUARIOS -> TOKENS DE ACESSO -> NOVO TOKEN -> API_GATEWAY* */
export const APPLICATION_GATEWAY_ENDPOINT = process?.env?.APPLICATION_GATEWAY_ENDPOINT ?? undefined;

/* ENDPOINT PRODUÇÃO GATEWAY MVPAY */
export const APPLICATION_TOKEN            = process?.env?.APPLICATION_TOKEN ?? undefined;

/* # PARCEITO DE CAPTURA */
export const APPLICATION_CAPTURE_PARTNER  = process?.env?.APPLICATION_CAPTURE_PARTNER ?? "TESTE-PERSONAL";

/* QUANTIDADES DE TRANSACÇÕES A SEREM GERDAAS */
export const APPLICATION_NUM_REGISTROS    = parseInt(process?.env?.APPLICATION_NUM_REGISTROS || '10');

/* LISTA DE DOCUMENTOS / MIDS A SER GERADDA ALEATÓRIAMENTE */
export const APPLICATION_DOCUMENTS_LIST   = (process?.env?.APPLICATION_DOCUMENTS_LIST || '00000000000000').split(',').map(s => s.trim());

/* LISTA DE ADIQUIRESTES A SER GERADDA ALEATÓRIAMENTE */
export const APPLICATION_ACQUIRER_LIST    = (process?.env?.APPLICATION_ACQUIRER_LIST || '18,19,20,21,22').split(',').map(s => s.trim());

/* LISTA DE BANDEIRAS A SER GERADDA ALEATÓRIAMENTE */
export const APPLICATION_BRANDS_LIST      = (process?.env?.APPLICATION_BRANDS_LIST || 'VISA,MASTERCARD,ELO').split(',').map(s => s.trim());

/* LISTA DE URL DE RETORNO DE RESPOSTA CASO HOUVER SUCESSO OU FALHA NO PROCRESSAMENTO DA TRANSAÇÃO */
export const APPLICATION_WEBHOOK_URL      = (process?.env?.APPLICATION_WEBHOOK_URL || '').split(',').map(s => s.trim());